homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # Using a nearby restaurant so not worried about secreting this location.
  latitude: 35.6431
  longitude: -78.4549
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 104
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

# Enables the frontend
frontend:

recorder:
  purge_days: 5
  db_url: !secret my_db
  


# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

panel_iframe:
  video:
    title: 'Alarm Video'
    url: 'https://www.alarm.com/pda/'

media_player:
  - platform: braviatv
    host: !secret brav_host
  - platform: kodi
    host: !secret kodi_host

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - input_slider.internet_traffic_delta_in
      - input_slider.internet_traffic_delta_out
      - automation.monitor_traffic

# Alexa setup
alexa:
  intents: !include_dir_named alexa/
  

wemo:

# Text to speech
tts:
  - platform: google

sun:
ifttt:
  key: !secret iftt_api  
  
notify:
  - platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarm_user 
  password: !secret alarm_pw
  
cover:
  platform: garadget
  covers:
      !secret garage_id:
        username: !secret garadget_username
        password: !secret garadget_password
        name: Garage Door
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  
################################################
## Component Includes (Merge List)
################################################
automation: !include_dir_merge_list automation
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named group
input_select: !include_dir_merge_named input_select
input_slider: !include misc/input_slider.yaml
light: !include_dir_merge_list light
scene: !include_dir_merge_list scene 
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
zone: !include_dir_merge_list zone

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: !secret mqtt_pw

