homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # Using a nearby restaurant so not worried about secreting this location.
  latitude: 35.6431
  longitude: -78.4549
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 104
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include_dir_merge_named customize

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

media_player:
  - platform: braviatv
    host: !secret brav_host
  - platform: kodi
    host: !secret kodi_host

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - input_slider.internet_traffic_delta_in
      - input_slider.internet_traffic_delta_out
      - automation.monitor_traffic

# Alexa setup
alexa:
  intents: !include_dir_named alexa/

      
# Text to speech
tts:
  - platform: google

notify:
  - platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarm_user 
  password: !secret alarm_pw
  
  
################################################
## Component Includes (Merge List)
################################################
sensor: !include_dir_merge_list sensor
input_select: !include misc/input_select.yaml
input_slider: !include misc/input_slider.yaml
device_tracker: !include device_tracker.yaml
automation: !include_dir_merge_list automation
light: !include_dir_merge_list light
zone: !include_dir_merge_list zone
group: !include_dir_merge_named group
scene: !include_dir_merge_list scene 

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: raspberry

