homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  # Using a nearby restaurant so not worried about secreting this location.
  latitude: 35.6431
  longitude: -78.4549
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 104
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather
sensor:
  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature

# Text to speech
tts:
  platform: google


mqtt:
  broker: !secret mqtt_broker
  port: 12464
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pw



device_tracker: !include device_tracker.yaml
  


alarm_control_panel:
  platform: alarmdotcom
  username: !secret alarm_user 
  password: !secret alarm_pw
  
  
################################################
## Component Includes (Merge List)
################################################

automation: !include_dir_merge_list automation
light: !include_dir_merge_list light
zone: !include_dir_merge_list zone

group: !include_dir_merge_named group  
  