- platform: unifi
  host: !secret unifi_host
  verify_ssl: False
  username: !secret unifi_user
  password: !secret unifi_pw
- platform: icloud
  username: !secret bicloud_user
  password: !secret bicloud_pw
  account_name: bdub
