- platform: asuswrt
  host: 192.168.1.1
  username: admin
  password: !secret wrt_pw
  interval_seconds: 10
  consider_home: 60
  track_new_devices: yes
  protocol: telnet
- platform: icloud
  username: !secret bicloud_user
  password: !secret bicloud_pw
  account_name: bdub
