################################################################
## Light
################################################################

################################################
## Philips Hue
################################################

- platform: hue
  host: !secret hue_host
  allow_unreachable: true
  allow_hue_groups: false