- platform: template
  sensors:
    garage_door_status:
      friendly_name: 'State of the door'
      value_template: '{{ states.cover.garage_door.state }}'
    garage_door_time_in_state:
      friendly_name: 'Time Since Change'
      value_template: '{{ states.cover.garage_door.attributes["time in state"] }}'
    garage_door_wifi_signal_strength:
      friendly_name: 'WiFi Strength'
      value_template: '{{ states.cover.garage_door.attributes["wifi signal strength (dB)"] }}'
      unit_of_measurement: 'dB'
    garage_door_reflection_rate:
      friendly_name: 'Reflection Rate'
      value_template: '{{ states.cover.garage_door.attributes["sensor reflection rate"] }}' 
      
      