- platform: snmp
  name: snmp_wan_in
  host: 192.168.1.1
  baseoid: 1.3.6.1.2.1.2.2.1.10.2
  
- platform: snmp
  name: snmp_wan_out
  host: 192.168.1.1
  baseoid: 1.3.6.1.2.1.2.2.1.16.2
  




- platform: template
  sensors:
    internet_speed_in:
      friendly_name: 'Internet Speed Down'
      value_template: '{{ ((states.input_slider.internet_traffic_delta_in.state | float ) / 1000000 ) | round(2) }}'
      unit_of_measurement: 'Mbps'

- platform: template
  sensors:
    internet_speed_out:
      friendly_name: 'Internet Speed Up'
      value_template: '{{ ((states.input_slider.internet_traffic_delta_out.state | float ) / 1000000 ) | round(2) }}'
      unit_of_measurement: 'Mbps'

- platform: statistics
  name: 'WAN Traffic IN'
  entity_id: sensor.internet_speed_in

- platform: statistics
  name: 'WAN Traffic OUT'
  entity_id: sensor.internet_speed_out       