- alias: arm_away_when_sheena_gone
  trigger:
    - platform: state
      entity_id: device_tracker.sheenasiphone
      from: 'home'
      to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.biphone_brian
        state: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_away
