- alias: arm_away_when_sheena_gone
  condition:
    - condition: state
      entity_id: device_tracker.sheenasiphone
      from: 'home'
      to: 'not_home'
    - condition: and
      entity_id: device_tracker.briansiphone
      state: 'not_home'


  action:
    - service: alarm_control_panel.alarm_arm_away