- alias: arm_away_when_brian_gone
  trigger:
    - platform: state
      entity_id: device_tracker.biphone_brian
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: alarm_control_panel.alarmcom
      state: 'disarmed'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.siphone_sheena
        state: 'not_home'
  
  action:
    - service: alarm_control_panel.alarm_arm_away
