- alias: arm_away
  trigger:
    - platform: state
      entity_id: device_tracker.sheenasiphone, device_tracker.briansiphone
      from: 'home'
      to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: alarm_control_panel.alarmcom
        state: 'disarmed'
      - condition: state
        entity_id: device_tracker.briansiphone
        state: 'not_home'
        for:
          minutes: 5
      - condition: state
        entity_id: device_tracker.sheenasiphone
        state: not_home
        for:
          minutes: 5
      - condition: or
        conditions:
          - condition: state
            entity_id: device_tracker.briansiphone
            state: 'brian_work'
          - condition: state
            entity_id: device_tracker.sheenasiphone
            state: 'sheena_work'
  action:
    - service: alarm_control_panel.alarm_arm_away
