- alias: arm_away_when_sheena_gone
  trigger:
    - platform: state
      entity_id: device_tracker.sheenasiphone
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: alarm_control_panel.alarmcom
      state: 'disarmed'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.briansiphone
        state: 'not_home'
        for:
          minutes: 10
      - condition: state
        entity_id: device_tracker.sheenasiphone
        state: not_home
        for:
          minutes: 5
  action:
    - service: alarm_control_panel.alarm_arm_away
