- alias: arm_away
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarmcom
      state: "disarmed"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_away
    - service: notify.notify
      data:
        message: "System has been armed to away"
        title: "Arm Away"
