- alias: bedtime
  trigger:
    - platform: time
      after: '21:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        weekday:
          - mon
          - tues
          - wed
          - thu

  action:
    - service: light.turn_off
      entity_id: group.all_lights