- alias: disarm_family_home
  trigger:
    - platform: state
      entity_id: device_tracker.briansiphone, device_tracker.sheenasiphone
      from: 'not_home'
      to: 'home'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.alarmcom
        state: "armed_home"
      - condition: state
        entity_id: alarm_control_panel.alarmcom
        state: "armed_away"
  action:
    - service: alarm_control_panel.alarm_disarm
    - service: notify.notify
      data:
        message: "System has been disarmed"
        title: "System Disarmed"
