##################################################
## Garadget automations, forked from https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/automation/garadget.yaml
##
##################################################

- alias: Garadget Reflection Rates
  hide_entity: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.garage_door_reflection_rate
      below: 85

  condition:
    - condition: template
      value_template: "{{ states('cover.garage_door') == 'closed' }}"
      
  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Check Garage Door Reflection:'
        value2: "{{ states('sensor.small_garage_reflection_rate')}}"
        value3: ""
        
##############################################################################

- alias: Is the Garage door Open at night - Checks every 60 minutes or 5 minutes after we drive away.
  hide_entity: True
  trigger:
    - platform: time
      minutes: '/60'
      seconds: 00
    - platform: state
      entity_id: group.family
      state: not_home
      for: 00:05:00

  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: group.family
            state: not_home
            for: 00:05:00
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ states('cover.garage_door') == 'opened' }}"
      - condition: and
        conditions:
          - condition: sun
            after: 'sunset'
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ states('cover.garage_door') == 'opened' }}"

  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Check Garage Door:'
        value2: "{{ states('cover.small_garage')}}"
        value3: ""