- alias: "Update iCloud Sheena Iphone"
  trigger:
    - platform: state
      entity_id: device_tracker.sheenasiphone
    - platform: time
      minutes: '/15'
      seconds: 0
  action:
    - service: device_tracker.icloud_set_interval
      data:
        device_name: sheenasiphone
        interval: 900