- alias: "Update iCloud"
  trigger:
    - platform: state
      entity_id: device_tracker.briansiphone, device_tracker.sheenasiphone, device_tracker.briansapple_watch
    - platform: time
      minutes: '/15'
      seconds: 0
  action:
    - service: device_tracker.icloud_set_interval
      data:
        device_name: briansiphone
        interval: 900
    - service: device_tracker.icloud_set_interval
      data:
        device_name: sheenasiphone
        interval: 900
    - service: device_tracker.icloud_set_interval
      data:
        device_name: briansapple_watch
        interval: 900
        