- alias: "Update iCloud Brian Watch"
  trigger:
    - platform: state
      entity_id: device_tracker.briansapple_watch
    - platform: time
      minutes: '/30'
      seconds: 0
  action:
    - service: device_tracker.icloud_set_interval
      data:
        device_name: briansapple_watch
        interval: 1800