- alias: turn_on_light_sun_sets
  initial_state: True
  hide_entity: False
  trigger:
    - platform: sun
      event: sunset

  action:
    - service: light.turn_on
      entity_id: group.garage
    - service: light.turn_on
      entity_id: group.living_room