- alias: turn_off_lights_sunrise
  trigger:
    - platform: state
      entity_id: sun.sun
      state: above_horizon
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_lights
        state: 'on'
      - condition: time
        after: "7:00:00"
        before: "8:00:00"
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.notify
      data:
        message: "Lights have been turned off due to sunrise"
        title: "Sunrise trigger fired"