- alias: turn_off_lights_sunrise
  trigger:
    - platform: state
      entity_id: sun.sun
      state: above_horizon
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_lights
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: group.all_lights