- alias: turn_on_lights_sunset
  trigger:
    - platform: state
      entity_id: sun.sun
      state: below_horizon
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_lights
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.all_lights