- alias: turn_on_lights_sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_lights
        state: 'off'
      - condition: time
        after: "18:00:00"
        before: "21:00:00"

  action:
    - service: light.turn_on
      entity_id:
        - group.bedroom_lights_card
        - group.living_room_lights_card
        - light.garage_left
        - light.garage_right
        - light.back_door
      data:
        transition: 300
        brightness: 144
        xy_color: [0.5016, 0.4151]
        rgb_color: [243, 179, 80]
        color_temp: 443
    - service: notify.notify
      data:
        message: "Lights have been turned on due to sunset"
        title: "Sunset trigger fired"
