- alias: Monitor Traffic

  trigger:
    platform: state
    entity_id: sensor.snmp_wan_in

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.internet_traffic_delta_in
        value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'

- alias: Monitor Traffic

  trigger:
    platform: state
    entity_id: sensor.snmp_wan_out

  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.internet_traffic_delta_out
        value: '{{ ((trigger.to_state.state | int - trigger.from_state.state | int) * 8 ) / ( as_timestamp(trigger.to_state.last_updated) - as_timestamp(trigger.from_state.last_updated) ) }}'