################################################################
## Packages / AlarmDotCom
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.alarmdotcom: &customize
      homebridge_hidden: true
      package: 'alarmdotcom'

   alarm_control_panel.alarmcom:
     <<: *customize
     friendly_name: "Alarm System"

   group.alarm_system:
     <<: *customize
     friendly_name: "Alarm System"

   automation.armed_away:
     <<: *customize
     friendly_name: "Arm Away"
     icon: mdi:security-home

   automation.disarm_family_home:
     <<: *customize
     friendly_name: "Disarm Family Home"
     icon: mdi:security-home

################################################
## Group
################################################

group:
  alarm_system:
    control: hidden
    entities:
      - alarm_control_panel.alarmcom

################################################
## Automation
################################################

automation:
  - alias: arm_away
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarmcom
        state: "disarmed"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.family
          state: 'not_home'
    action:
      - service: alarm_control_panel.alarm_arm_away
      - service: notify.notify
        data:
          message: "System has been armed to away"
          title: "Arm Away"

  - alias: disarm_family_home
    trigger:
      - platform: state
        entity_id: device_tracker.brians_iphone, device_tracker.sheenas_iphone
        from: 'not_home'
        to: 'home'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.alarmcom
          state: "armed_home"
        - condition: state
          entity_id: alarm_control_panel.alarmcom
          state: "armed_away"
    action:
      - service: alarm_control_panel.alarm_disarm
      - service: notify.notify
        data:
          message: "System has been disarmed"
          title: "System Disarmed"
