##############################################################
## Packages / Dog
##############################################################

automation:
  - alias: Feed Dog Reminder
    trigger:
      - platform: time
        after: '11:30:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.family
          state: 'home'
    action:
      - service: script.voice_notify
        data_template:
          value1: Don't forget to feed Daisey its lunch time for her
          value2: ""
