############################################
# Packages / Presence Detection
############################################
homeassistant:
  customize:
    device_tracker.sheenasiphone:
      friendly_name: 'Sheena'
      hidden: False

    device_tracker.briansiphone:
      friendly_name: 'Brian'
      hidden: False



####### MODES
input_boolean:
  away:
    name: Away
    icon: mdi:account-off
