#####################################################
## Packages / Sunset
#####################################################

#####################################################
## Customize
#####################################################

homeassistant:
  customize:
    packages.sunset: &customize
      homebridge_hidden: false
      package: 'sunrise'

    automation.sunset:
      <<: *customize
      friendly_name: "Sunset"
      icon: mdi:weather-sunset

######################################################
## Automation
######################################################

automation:
  - alias: sunset
    trigger:
      - platform: sun
        event: sunset
        offset: '-00:30:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: group.all_lights
          state: 'off'
        - condition: time
          after: "18:00:00"
          before: "21:00:00"

    action:
      - service: light.turn_on
        entity_id:
          - group.master_bedroom
          - group.living_room
          - light.garage_left
          - light.garage_right
          - light.back_door
        data:
          transition: 300
          brightness: 144
          xy_color: [0.5016, 0.4151]
          rgb_color: [243, 179, 80]
          color_temp: 443
      - service: notify.notify
        data:
          message: "Lights have been turned on due to sunset"
          title: "Sunset trigger fired"
